version: "3.9"
services:
  db:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: Your_password123
      ACCEPT_EULA: Y
    ports:
    - 1433:1433
    volumes:
    - ./sqlserver/data:/var/opt/mssql/data
    - ./sqlserver/log:/var/opt/mssql/log